### ISSUE TITLE
Pear requires a nightly or dev version of Rust still

### ISSUE THREAD

**Issue by stefaneicher** [SergioBenitez/Pear#17]
Short:

I get this error and it seems weird to me. ( I am new to Rust)

Error: Rocket requires a nightly or dev version of Rust.
Installed version is: 1.35.0 (2019-05-20). Minimum required: 1.32.0-nightly (2018-11-23).

I have seen https://github.com/SergioBenitez/Pear/issues/13 and could fix it by 
running "rustup default nightly" but should  Should Pear/Rocket not be in a state where it also runs with  1.35.0?

Log:

I run that 
"
git clone https://github.com/SergioBenitez/Rocket
cd Rocket
git checkout v0.4.1
cd examples/hello_world
cargo run
"

an got:

UM01324:rocket taaeist1$ git clone https://github.com/SergioBenitez/Rocket
Cloning into 'Rocket'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 16048 (delta 0), reused 3 (delta 0), pack-reused 16039
Receiving objects: 100% (16048/16048), 3.34 MiB | 1.25 MiB/s, done.
Resolving deltas: 100% (9826/9826), done.
UM01324:rocket taaeist1$ cd Rocket
UM01324:Rocket taaeist1$ git checkout v0.4.1
Note: checking out 'v0.4.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at f1f09f1... New version: 0.4.1.
UM01324:Rocket taaeist1$ cd examples/hello_world
UM01324:hello_world taaeist1$ 
UM01324:hello_world taaeist1$ cargo run
    Updating crates.io index
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling matches v0.1.8
   Compiling yansi v0.4.0
   Compiling version_check v0.1.5
   Compiling cfg-if v0.1.9
   Compiling libc v0.2.57
   Compiling smallvec v0.6.9
   Compiling cc v1.0.37
   Compiling syn v0.15.34
   Compiling byteorder v1.3.1
   Compiling httparse v1.3.3
   Compiling percent-encoding v1.0.1
   Compiling bitflags v1.0.4
   Compiling untrusted v0.6.2
   Compiling safemem v0.3.0
   Compiling traitobject v0.1.0
   Compiling yansi v0.5.0
   Compiling language-tags v0.2.2
   Compiling typeable v0.1.2
   Compiling serde v1.0.92
   Compiling indexmap v1.0.2
   Compiling memchr v2.2.0
   Compiling state v0.4.1
   Compiling log v0.4.6
   Compiling unicode-bidi v0.3.4
   Compiling unicode-normalization v0.1.8
   Compiling pear_codegen v0.1.2
   Compiling unicase v1.4.2
   Compiling rocket_codegen v0.4.1 (/Users/taaeist1/CLionProjects/rocket/Rocket/core/codegen)
   Compiling rocket v0.4.1 (/Users/taaeist1/CLionProjects/rocket/Rocket/core/lib)
   Compiling log v0.3.9
error: failed to run custom build command for `pear_codegen v0.1.2`
process didn't exit successfully: `/Users/taaeist1/CLionProjects/rocket/Rocket/target/debug/build/pear_codegen-2edc7821f01b15da/build-script-build` (exit code: 101)
--- stderr
Error: Pear requires a nightly or dev version of Rust.
Installed version is: 1.35.0 (2019-05-20). Minimum required: 1.31.0-nightly (2018-10-05).
thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', /Users/taaeist1/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.1.2/build.rs:31:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by revred** [comment]
This one kept me thinking for a while. Should really be fixed to work as standard.

**Comment by SergioBenitez** [comment]
No, Rocket still requires nightly. See https://github.com/SergioBenitez/Rocket/issues/19 for why. Pear likely doesn't _require_ nightly any more, but as of now, it does make use of nightly features. Until Rocket is ready to be compiled on stable, there isn't a great reason to migrate Pear off of nightly.

**Comment by FibreFoX** [comment]
Even if Rocket isn't ready to work with rust-stable ... it might reduce the perception that this "limitation" belongs to Pear, but is a issue of Rocket.

Just a small request to rethink the decision to have Pear requiring nightly.

**Comment by SergioBenitez** [comment]
@FibreFoX I've recently reduced the number of nightly feature usage in Pear to one, specialization, and I'm actively working on a work-around for that as well.
