### ISSUE TITLE
Allow use with `RUSTC_BOOTSTRAP`

### ISSUE THREAD

**Issue by estebank** [SergioBenitez/Pear#18]
In https://github.com/SergioBenitez/Pear/blob/d9015f9b81998daf2dbeffd3ebf8df2873a58ae0/codegen/build.rs#L20 it'd be nice to also check for the env variable `RUSTC_BOOTSTRAP=1` to allow using latest stable compiler with nightly features. Using `RUSTC_BOOTSTRAP` is a hack and not _ideal_, but right now Pear (and Rocket) are the only things keeping us from using a stable compiler.

This could also alternatively be supported in https://github.com/SergioBenitez/version_check instead.

**Comment by SergioBenitez** [comment]
Looks like we probably shouldn't do this after all. Closing.
