### ISSUE TITLE
Readme could be improved.

### ISSUE THREAD

**Issue by gilescope** [SergioBenitez/Pear#22]
It would be great if the readme said what pear was and maybe who the big users of pear was and why it was great and why you would or would not want to use it.

**Comment by SergioBenitez** [comment]
I'm with you. As soon as the library is ready for its public debut, we'll ship a much better README and much more.

**Comment by djensen47** [comment]
But what _will_ it do? Just a hint please and thank you.

**Comment by VeryCleverName3** [comment]
A pear is a fruit.
