### ISSUE TITLE
doc decorator in macros.rs has typo

### ISSUE THREAD

**Issue by kitsuneninetails** [SergioBenitez/Pear#28]
https://github.com/SergioBenitez/Pear/blob/80112eedec7809c59e525f6852490c49856a6550/lib/src/macros.rs#L79

This should be "hidden", not "hiden".  This now fails on nightly rust.

**Comment by SergioBenitez** [comment]
Fixed in d137aa1df314e2e199470e1f54b931bf859ade89.
