### ISSUE TITLE
Please add repository to manifest

### ISSUE THREAD

**Issue by mohe2015** [SergioBenitez/Pear#32]
Hi,

please add the `repository` field to all `Cargo.toml`s (https://doc.rust-lang.org/cargo/reference/manifest.html#the-repository-field).
Thanks.

Kind regards
Moritz

**Comment by SergioBenitez** [comment]
Could you tell me why this might be important to you, aside from discoverability?

**Comment by mohe2015** [comment]
> Could you tell me why this might be important to you, aside from discoverability?

I'm auditing my dependencies and one step is comparing the crates.io source of the package with the git source and there this field helps to automatically find the repository.
