### ISSUE TITLE
codegen compile errors on syntax::ast types

### ISSUE THREAD

**Issue by Martin1887** [SergioBenitez/Pear#4]
Rocket (my own fork based on master) build fails with the following errors after fixing #3, it seems that a `syntax::codemap::Spanned` is expected instead `syntax::ast::Ident`:

    error[E0609]: no field `name` on type `&syntax::ast::MetaItem`
      --> codegen/src/utils/meta_item_ext.rs:13:57
       |
    13 |             MetaItemKind::NameValue(ref l) => Some((&mi.name, l)),
       |                                                         ^^^^

    error[E0609]: no field `node` on type `&syntax::ast::Ident`
      --> codegen/src/utils/arg_ext.rs:18:60
       |
    18 |             PatKind::Ident(_, ref ident, _) => Some(&ident.node),
       |                                                            ^^^^

    error[E0308]: mismatched types
      --> codegen/src/utils/parser_ext.rs:57:20
       |
    57 |                 Ok(ident)
       |                    ^^^^^ expected struct `syntax::codemap::Spanned`, found struct `syntax::ast::Ident`
       |
       = note: expected type `syntax::codemap::Spanned<syntax::ast::Ident>`
                  found type `syntax::ast::Ident`

    error[E0599]: no method named `name` found for type `&syntax::ast::MetaItem` in the current scope
       --> codegen/src/parser/route.rs:172:52
        |
    172 |         if let Ok(method) = Method::from_str(&word.name().as_str()) {
        |                                                    ^^^^
        |
        = help: items from traits can only be used if the trait is implemented and in scope
        = note: the following trait defines an item `name`, perhaps you need to implement it:
                candidate #1: `utils::arg_ext::ArgExt`

    error[E0599]: no method named `name` found for type `&syntax::ast::MetaItem` in the current scope
       --> codegen/src/parser/route.rs:178:62
        |
    178 |         let msg = format!("'{}' is not a valid method", word.name());
        |                                                              ^^^^
        |
        = help: items from traits can only be used if the trait is implemented and in scope
        = note: the following trait defines an item `name`, perhaps you need to implement it:
                candidate #1: `utils::arg_ext::ArgExt`

    error[E0609]: no field `identifier` on type `&mut syntax::ast::PathSegment`
      --> codegen/src/macros/mod.rs:19:14
       |
    19 |     last_seg.identifier = last_seg.identifier.prepend(prefix);
       |              ^^^^^^^^^^

    error[E0609]: no field `identifier` on type `&mut syntax::ast::PathSegment`
      --> codegen/src/macros/mod.rs:19:36
       |
    19 |     last_seg.identifier = last_seg.identifier.prepend(prefix);
       |                                    ^^^^^^^^^^

    error[E0308]: mismatched types
       --> codegen/src/macros/uri.rs:136:63
        |
    136 |         let (qself, path) = ecx.qpath(ty.clone(), trait_path, method);
        |                                                               ^^^^^^ expected struct `syntax::ast::Ident`, found struct `syntax::codemap::Spanned`
        |
        = note: expected type `syntax::ast::Ident`
                   found type `syntax::codemap::Spanned<syntax::ast::Ident>`

    error: aborting due to 8 previous errors

    Some errors occurred: E0308, E0599, E0609.
    For more information about an error, try `rustc --explain E0308`.
    error: Could not compile `rocket_codegen`.
    warning: build failed, waiting for other jobs to finish...
    error: build failed

**Comment by SergioBenitez** [comment]
You need to cargo update.
