### ISSUE TITLE
...what in the world even IS this?

### ISSUE THREAD

**Issue by icefoxen** [SergioBenitez/Pear#5]
:confused:

**Comment by SergioBenitez** [comment]
A pear is a fruit.

**Comment by icefoxen** [comment]
No.  No no no no no.  See, when you lead one of the flagship parts of the rust ecosystem, you don't get to brush off questions with a joke.  I actually want to know.

**Comment by andrewbanchich** [comment]
It's definitely something food related.

**Comment by timClicks** [comment]
If you look through the examples, you'll see that Pear is a parser generator library. Similar to [nom](https://github.com/Geal/nom).

**Comment by nuharaf** [comment]
Is this a reference to lemon ~~parser~~ fruit
